#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1
PROG=/usr/local/bin/openwrt_cm4_stats_run.sh

start_service() {

	procd_open_instance
	procd_set_param command "$PROG"
        procd_set_param env SEND=1
	procd_set_param respawn
        procd_set_param stderr 1
	procd_close_instance
}
